module.exports = [
  {
    year: "2017",
    make: "Buick",
    model: "Regal",
    stock: "F1261",
    bodyShop: "not-needed",
    majorService: "not-needed",
    detail: "done",
    photos: "done",
    description: "done",
    gas: "done",
    safetyCheck: "done",
    stickers: "done",
    priceTag: "done",
    severity: null,
    isSold: false,
    notes: [
      {
        date: "3/31/22",
        user: "user 1",
        body: "this is a note",
      },
    ],
  },
  {
    year: "2015",
    make: "Infiniti",
    model: "Q40",
    stock: "F1159",
    bodyShop: "not-done",
    majorService: "not-done",
    detail: "not-done",
    photos: "not-done",
    description: "not-done",
    gas: "not-done",
    safetyCheck: "not-done",
    stickers: "not-done",
    priceTag: "not-done",
    severity: null,
    isSold: false,
    notes: [
      {
        date: "3/31/22",
        user: "user 2",
        body: "this is another note",
      },
    ],
  },
  {
    year: "2014",
    make: "Ford",
    model: "Escape",
    stock: "F1349",
    bodyShop: "not-needed",
    majorService: "not-needed",
    detail: "done",
    photos: "not-done",
    description: "not-done",
    gas: "done",
    safetyCheck: "not-done",
    stickers: "done",
    priceTag: "done",
    severity: null,
    isSold: false,
    notes: [
      {
        date: "3/31/22",
        user: "Michael Camara",
        body: "this is a note",
      },
    ],
  },
  {
    year: "2016",
    make: "BMW",
    model: "535",
    stock: "F1151",
    bodyShop: "not-needed",
    majorService: "not-done",
    detail: "done",
    photos: "done",
    description: "done",
    gas: "done",
    safetyCheck: "done",
    stickers: "done",
    priceTag: "done",
    severity: null,
    isSold: false,
    notes: [
      {
        date: "3/31/22",
        user: "Michael Camara",
        body: "this is a note",
      },
    ],
  },
  {
    year: "2004",
    make: "Dodge",
    model: "Ram 2500",
    stock: "F1334M",
    bodyShop: "not-needed",
    majorService: "not-done",
    detail: "done",
    photos: "not-done",
    description: "not-done",
    gas: "not-done",
    safetyCheck: "not-done",
    stickers: "done",
    priceTag: "done",
    severity: null,
    isSold: true,
    notes: [
      {
        date: "3/31/22",
        user: "Michael Camara",
        body: "this is a note",
      },
    ],
  },
];
